# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'

        speaker_ftp:
            ftp:
                host: ~
                port: 21
                username: ~
                password: ~
                root: ~
                ssl: ~
                timeout: ~
                permPrivate: ~
                permPublic: ~
                passive: ~
    filesystems:
        default_filesystem:
            adapter: speaker_ftp
            alias: League\Flysystem\Filesystem
